### ISSUE TITLE
programmers - 프로세스

### ISSUE THREAD

**Issue by suw0n** [boj-dgsw/ps#4]
이 코드의 시간복잡도를 개선할 수 있는 방법을 고민해봅시다. (문제 풀고 코드 올려주세요~ 언어 제한 X)

```java
import java.util.LinkedList;
import java.util.Queue;
import java.util.concurrent.atomic.AtomicBoolean;

public class Solution {

    public int solution(int[] priorities, int location) {
        int answer = 0;
        Queue<Process> que = new LinkedList<>();

        for(int i = 0; i<priorities.length; i++) {
            que.add(new Process(i, priorities[i]));
        }

        int cnt = 1;
        while(!que.isEmpty()) {
            AtomicBoolean canWork = new AtomicBoolean(true);
            Process process = que.poll();

            que.forEach(p -> {
                if(p.priority > process.priority) {
                    canWork.set(false);
                }
            });

            if(canWork.get()) {
                if(process.index == location) {
                    answer = cnt;
                }
                cnt++;
            } else {
                que.add(process);
            }
        }

        return answer;
    }

    static class Process {

        int index, priority;

        Process(int index, int priority) {
            this.index = index;
            this.priority = priority;
        }

    }

}

**Comment by Hekaline** [comment]
프로그래머스에서 자바로 문제를 안 풀어봐서 그런데 아토믹 불리언은 왜 사용하는 것인가요? 멀티스레드 환경인가요?

**Comment by Hekaline** [comment]
참고로 C++을 사용하면 같은 시간복잡도에 더 빠른 프로그램 속도를 기대할 수 있습니다. (푸하하)

**Comment by suw0n** [comment]
> 프로그래머스에서 자바로 문제를 안 풀어봐서 그런데 아토믹 불리언은 왜 사용하는 것인가요? 멀티스레드 환경인가요?

네^^ 맞습니다...

**Comment by Hekaline** [comment]
`#include <string>
#include <vector>
#include <queue>
#include <algorithm>

using namespace std;

class Process
{
public:
    int priority;
    int location;
    
public:
    Process(int _priority, int _location) : 
        priority(_priority), location(_location){}
};

int solution(vector<int> priorities, int location) 
{
    int answer = 1;
    
    // priorities를 옮길 큐
    queue<Process> q;
    
    // 우선순위를 오름차순으로 정렬할 벡터
    vector<int> priorityStack = priorities;
    sort(priorityStack.begin(), priorityStack.end()); // 곧바로 정렬
    
    
    for (int i = 0; i < priorities.size(); i++)
    {
        q.push(Process(priorities[i], i));
    } 
    
    while(q.empty() == false)
    {
        // 현재 프로세스를 큐에서 꺼내온다.
        Process currProcess = q.front(); q.pop();
        
        // 현재 남은 프로세스들의 가장 높은 우선순위와 현재 프로세스 우선순위가 같은가?
        if (currProcess.priority == priorityStack.back())
        {
            if (currProcess.location == location)
            {
                // 우선순위를 찾고자 하는 위치와 같다면 정답 반환 및 종료
                return answer;
            } else
            {
                // 우선순위가 가장 높은 걸 찾았지만 위치가 다른 경우
                answer += 1;
                priorityStack.pop_back();
            }
        } else
        {
            q.push(currProcess);
        }
    }
    
    return answer;
}`

**Comment by Hekaline** [comment]
```cpp
#include <string>
#include <vector>
#include <queue>
#include <algorithm>

using namespace std;

class Process
{
public:
    int priority;
    int location;
    
public:
    Process(int _priority, int _location) : 
        priority(_priority), location(_location){}
};

int solution(vector<int> priorities, int location) 
{
    int answer = 1;
    
    // priorities를 옮길 큐
    queue<Process> q;
    
    // 우선순위를 오름차순으로 정렬할 벡터
    vector<int> priorityStack = priorities;
    sort(priorityStack.begin(), priorityStack.end()); // 곧바로 정렬
    
    
    for (int i = 0; i < priorities.size(); i++)
    {
        q.push(Process(priorities[i], i));
    } 
    
    while(q.empty() == false)
    {
        // 현재 프로세스를 큐에서 꺼내온다.
        Process currProcess = q.front(); q.pop();
        
        // 현재 남은 프로세스들의 가장 높은 우선순위와 현재 프로세스 우선순위가 같은가?
        if (currProcess.priority == priorityStack.back())
        {
            if (currProcess.location == location)
            {
                // 우선순위를 찾고자 하는 위치와 같다면 정답 반환 및 종료
                return answer;
            } else
            {
                // 우선순위가 가장 높은 걸 찾았지만 위치가 다른 경우
                answer += 1;
                priorityStack.pop_back();
            }
        } else
        {
            q.push(currProcess);
        }
    }
    
    return answer;
}
```

**Comment by Hekaline** [comment]
일단 풀어보았는데 정렬한 우선순위 배열 안 쓰고 다시 한 번 제출한 후에 시간 비교해 보겠습니다
참고로 저 코드로 나온 시간 0.01ms~0.02ms 사이입니다

**Comment by suw0n** [comment]
좋은 접근이네요~
