### ISSUE TITLE
boj - N과 M(4)

### ISSUE THREAD

**Issue by suw0n** [boj-dgsw/ps#5]
백트레킹 공부하고 있는데 제가 부족해서 발상이 안떠오르네요. 도움 부탁드립니다.
https://www.acmicpc.net/problem/15652

**Comment by wlals1126** [comment]
거의 대부분의 사람들이 백트레킹을 접근하는 방식 중 하나가 재귀적으로 접근하는 방식인데요, N과 M(4) 같은 문제도 재귀 함수를 구현한 후 선택된 수열이 주어진 조건을 만족하는지 확인하고 조건에 맞는 수열을 출력하면 쉽게 푸실 수 있을겁니다.
더 궁금하신거 있으시면 코멘트 달아주시면 감사하겠습니다 :)

**Comment by suw0n** [comment]
재귀적으로 생각하는게 어려워요.ㅜㅜ 빨리 도와주세요.

**Comment by wlals1126** [comment]
```
예제 입력 2 
4 2
예제 출력 2 
1 1
1 2
1 3
1 4
2 2
2 3
2 4
3 3
3 4
4 4
```
이 예제로 설명하자면, 먼저  1부터 4까지의 자연수 중에서 2개의 수열을 찾아야 함.
- 첫 번째 자리 수 = 1, 2, 3, 4
- 두 번째 자리 수 = 첫 번째 자리 수 보다 같거나 큰 수
- 세 번쨰 자리수 = 두 번째 자리 수 보다 같거나 큰 수
- 네 번째 또한 같거나 큰수

1. 첫 번째 자리에 1 선택, 두 번째 자리에는 1 이상의 수가 와야함 그래서 1, 2, 3, 4가 올 수 있음. 따라서 (1, 1), (1, 2), (1, 3), (1, 4)가 됨
2. 첫 번째 자리에 2 선택, 두 번째 자리에는 2 이상의 수가 와야함 그래서 2, 3, 4가 올 수 있음. 따라서 (2, 2), (2, 3), (2, 4)가 됨
3. 첫 번째 자리에 3 선택, 두 번째 자리에는 3 이상의 수가 와야함 그래서 3, 4가 올 수 있음 따라서 (3, 3), (3, 4)가 됨
4. 첫 번째 자리에 4 선택, 두 번째 자리에는 4 이상의 수가 와야함 그래서 4가 올 수 있음 따라서 (4, 4)가 됨

**Comment by wlals1126** [comment]
개인적으로 설명해드리겠습니다~
